# Generated by Django 4.2.4 on 2023-08-01 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=200)),
                ('cor', models.CharField(choices=[('#ff7a7a', 'Vermelho'), ('#fed148', 'Amarelo'), ('#92fc8d', 'Verde'), ('#55adfb', 'Azul'), ('#f592fa', 'Roxo'), ('#cc7aff', 'Rosa'), ('#ffffff', 'Branco')], default=None, max_length=8)),
                ('status', models.CharField(choices=[('Razoável', 'Razoável'), ('Médio', 'Médio'), ('Alto', 'Alto')], default=None, max_length=8)),
                ('data_inicio', models.DateField(default=None)),
                ('data_termino', models.DateField(default=None)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField(default=None)),
                ('data_termino', models.DateField(default=None)),
                ('completa', models.BooleanField(default=False)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='tasks.tarefa')),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_tarefa', to='usuarios.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], max_length=8)),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('convidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convidado', to='usuarios.userprofile')),
                ('projeto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='tasks.projeto')),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='usuarios.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.projeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.userprofile')),
            ],
        ),
    ]
