# Generated by Django 4.2.2 on 2023-08-07 16:49

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, default='', upload_to=usuarios.models.upload_to),
        ),
    ]
